version: '3'
services:
  node-app:
   container_name: node_app_container
   image: mostafa731/node-app
   ports:
    - 4000:4000 
   env_file:
    - ./.env
   depends_on:
    - redis    
  redis:
    image: redis  
  nginx:
    image: nginx:stable-alpine
    ports:
    - "8080:80"
    volumes:
     - ./nginx/myserver.config:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

volumes:
  mongo-db: