services:
  node-app:
   container_name: node_app_container
   build: 
     context: .
     target: development
   volumes:
      - ./src:/app/src:ro
   environment:
     -  NODE_ENV=development
   command: npm run start-dev
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example  