version: '3'
services:
  node-app:
   container_name: node_app_container
   image: mostafa731/node-app
   build: .
   volumes:
      - ./src:/app/src:ro
   ports:
   - 4000:4000 
   env_file:
    - ./.env